const data = {
    products:[
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            price: 120,
            image: '/images/p2.jpg',
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 140,
            brand: 'Lacoste',
            rating: 4.5,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 100,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'Puma Slim Pants',
            category: 'Pants',
            price: 80,
            image: '/images/p5.jpg',
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Adidas Fit Pants',
            category: 'Pants',
            price: 95,
            image: '/images/p6.jpg',
            brand: 'Adidas',
            rating: 5,
            numReviews: 15,
            description: 'high quality product',
        },
    ]
}

export default data;